//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use num_derive::FromPrimitive;
use thiserror::Error;

#[derive(Clone, Debug, Eq, Error, FromPrimitive, PartialEq)]
pub enum StatePassError {
    /// 6000 - The provided level is invalid or the maximum level has been reached.
    #[error("The provided level is invalid or the maximum level has been reached.")]
    InvalidLevel = 0x1770,
}

impl From<StatePassError> for solana_program_error::ProgramError {
    fn from(e: StatePassError) -> Self {
        solana_program_error::ProgramError::Custom(e as u32)
    }
}
