/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from "@solana/kit";

/** Event emitted when the NFT's metadata fields (like level or URI) are updated. */
export type NftMetadataUpdated = {
  /** The public key of the updated NFT Mint account. */
  nftMint: Address;
  /** The field key that was updated (e.g., "level" or "uri"). */
  field: string;
  /** The new value of the field. */
  value: string;
};

export type NftMetadataUpdatedArgs = NftMetadataUpdated;

export function getNftMetadataUpdatedEncoder(): Encoder<NftMetadataUpdatedArgs> {
  return getStructEncoder([
    ["nftMint", getAddressEncoder()],
    ["field", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ["value", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
  ]);
}

export function getNftMetadataUpdatedDecoder(): Decoder<NftMetadataUpdated> {
  return getStructDecoder([
    ["nftMint", getAddressDecoder()],
    ["field", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ["value", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getNftMetadataUpdatedCodec(): Codec<
  NftMetadataUpdatedArgs,
  NftMetadataUpdated
> {
  return combineCodec(
    getNftMetadataUpdatedEncoder(),
    getNftMetadataUpdatedDecoder(),
  );
}
