/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

/** Event emitted when a new StatePass NFT is successfully minted. */
export type NftMinted = {
  /** The public key of the new NFT Mint account. */
  nftMint: Address;
  /** The public key of the recipient (the signer/owner). */
  recipient: Address;
};

export type NftMintedArgs = NftMinted;

export function getNftMintedEncoder(): FixedSizeEncoder<NftMintedArgs> {
  return getStructEncoder([
    ["nftMint", getAddressEncoder()],
    ["recipient", getAddressEncoder()],
  ]);
}

export function getNftMintedDecoder(): FixedSizeDecoder<NftMinted> {
  return getStructDecoder([
    ["nftMint", getAddressDecoder()],
    ["recipient", getAddressDecoder()],
  ]);
}

export function getNftMintedCodec(): FixedSizeCodec<NftMintedArgs, NftMinted> {
  return combineCodec(getNftMintedEncoder(), getNftMintedDecoder());
}
