//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_pubkey::{pubkey, Pubkey};

/// `state_pass` program ID.
pub const STATE_PASS_ID: Pubkey = pubkey!("F3uXqosNaNUfi76dSGLQm8CFYdSyRfzZixrVhQNNLqUV");
