/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU8Decoder,
  getU8Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type AccountMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from "@solana/kit";
import { STATE_PASS_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const UPDATE_PASS_LEVEL_DISCRIMINATOR = new Uint8Array([
  217, 6, 118, 42, 76, 136, 172, 157,
]);

export function getUpdatePassLevelDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_PASS_LEVEL_DISCRIMINATOR,
  );
}

export type UpdatePassLevelInstruction<
  TProgram extends string = typeof STATE_PASS_PROGRAM_ADDRESS,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountNftAuthority extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountMint extends string
        ? WritableAccount<TAccountMint>
        : TAccountMint,
      TAccountNftAuthority extends string
        ? ReadonlyAccount<TAccountNftAuthority>
        : TAccountNftAuthority,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type UpdatePassLevelInstructionData = {
  discriminator: ReadonlyUint8Array;
  newLevel: number;
  newUri: string;
};

export type UpdatePassLevelInstructionDataArgs = {
  newLevel: number;
  newUri: string;
};

export function getUpdatePassLevelInstructionDataEncoder(): Encoder<UpdatePassLevelInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["newLevel", getU8Encoder()],
      ["newUri", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ]),
    (value) => ({ ...value, discriminator: UPDATE_PASS_LEVEL_DISCRIMINATOR }),
  );
}

export function getUpdatePassLevelInstructionDataDecoder(): Decoder<UpdatePassLevelInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["newLevel", getU8Decoder()],
    ["newUri", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getUpdatePassLevelInstructionDataCodec(): Codec<
  UpdatePassLevelInstructionDataArgs,
  UpdatePassLevelInstructionData
> {
  return combineCodec(
    getUpdatePassLevelInstructionDataEncoder(),
    getUpdatePassLevelInstructionDataDecoder(),
  );
}

export type UpdatePassLevelAsyncInput<
  TAccountMint extends string = string,
  TAccountNftAuthority extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  mint: Address<TAccountMint>;
  nftAuthority?: Address<TAccountNftAuthority>;
  tokenProgram?: Address<TAccountTokenProgram>;
  newLevel: UpdatePassLevelInstructionDataArgs["newLevel"];
  newUri: UpdatePassLevelInstructionDataArgs["newUri"];
};

export async function getUpdatePassLevelInstructionAsync<
  TAccountMint extends string,
  TAccountNftAuthority extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof STATE_PASS_PROGRAM_ADDRESS,
>(
  input: UpdatePassLevelAsyncInput<
    TAccountMint,
    TAccountNftAuthority,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  UpdatePassLevelInstruction<
    TProgramAddress,
    TAccountMint,
    TAccountNftAuthority,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? STATE_PASS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    mint: { value: input.mint ?? null, isWritable: true },
    nftAuthority: { value: input.nftAuthority ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.nftAuthority.value) {
    accounts.nftAuthority.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            110, 102, 116, 95, 97, 117, 116, 104, 111, 114, 105, 116, 121,
          ]),
        ),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb" as Address<"TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.nftAuthority),
      getAccountMeta(accounts.tokenProgram),
    ],
    data: getUpdatePassLevelInstructionDataEncoder().encode(
      args as UpdatePassLevelInstructionDataArgs,
    ),
    programAddress,
  } as UpdatePassLevelInstruction<
    TProgramAddress,
    TAccountMint,
    TAccountNftAuthority,
    TAccountTokenProgram
  >);
}

export type UpdatePassLevelInput<
  TAccountMint extends string = string,
  TAccountNftAuthority extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  mint: Address<TAccountMint>;
  nftAuthority: Address<TAccountNftAuthority>;
  tokenProgram?: Address<TAccountTokenProgram>;
  newLevel: UpdatePassLevelInstructionDataArgs["newLevel"];
  newUri: UpdatePassLevelInstructionDataArgs["newUri"];
};

export function getUpdatePassLevelInstruction<
  TAccountMint extends string,
  TAccountNftAuthority extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof STATE_PASS_PROGRAM_ADDRESS,
>(
  input: UpdatePassLevelInput<
    TAccountMint,
    TAccountNftAuthority,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): UpdatePassLevelInstruction<
  TProgramAddress,
  TAccountMint,
  TAccountNftAuthority,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? STATE_PASS_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    mint: { value: input.mint ?? null, isWritable: true },
    nftAuthority: { value: input.nftAuthority ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb" as Address<"TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.nftAuthority),
      getAccountMeta(accounts.tokenProgram),
    ],
    data: getUpdatePassLevelInstructionDataEncoder().encode(
      args as UpdatePassLevelInstructionDataArgs,
    ),
    programAddress,
  } as UpdatePassLevelInstruction<
    TProgramAddress,
    TAccountMint,
    TAccountNftAuthority,
    TAccountTokenProgram
  >);
}

export type ParsedUpdatePassLevelInstruction<
  TProgram extends string = typeof STATE_PASS_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    mint: TAccountMetas[0];
    nftAuthority: TAccountMetas[1];
    tokenProgram: TAccountMetas[2];
  };
  data: UpdatePassLevelInstructionData;
};

export function parseUpdatePassLevelInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedUpdatePassLevelInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      mint: getNextAccount(),
      nftAuthority: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getUpdatePassLevelInstructionDataDecoder().decode(instruction.data),
  };
}
