/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  type ParsedInitializeInstruction,
  type ParsedMintNftInstruction,
  type ParsedUpdatePassLevelInstruction,
} from "../instructions";

export const STATE_PASS_PROGRAM_ADDRESS =
  "F3uXqosNaNUfi76dSGLQm8CFYdSyRfzZixrVhQNNLqUV" as Address<"F3uXqosNaNUfi76dSGLQm8CFYdSyRfzZixrVhQNNLqUV">;

export enum StatePassAccount {
  NftAuthority,
}

export function identifyStatePassAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): StatePassAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([194, 127, 219, 16, 219, 18, 250, 12]),
      ),
      0,
    )
  ) {
    return StatePassAccount.NftAuthority;
  }
  throw new Error(
    "The provided account could not be identified as a statePass account.",
  );
}

export enum StatePassInstruction {
  Initialize,
  MintNft,
  UpdatePassLevel,
}

export function identifyStatePassInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): StatePassInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([175, 175, 109, 31, 13, 152, 155, 237]),
      ),
      0,
    )
  ) {
    return StatePassInstruction.Initialize;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([211, 57, 6, 167, 15, 219, 35, 251]),
      ),
      0,
    )
  ) {
    return StatePassInstruction.MintNft;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([217, 6, 118, 42, 76, 136, 172, 157]),
      ),
      0,
    )
  ) {
    return StatePassInstruction.UpdatePassLevel;
  }
  throw new Error(
    "The provided instruction could not be identified as a statePass instruction.",
  );
}

export type ParsedStatePassInstruction<
  TProgram extends string = "F3uXqosNaNUfi76dSGLQm8CFYdSyRfzZixrVhQNNLqUV",
> =
  | ({
      instructionType: StatePassInstruction.Initialize;
    } & ParsedInitializeInstruction<TProgram>)
  | ({
      instructionType: StatePassInstruction.MintNft;
    } & ParsedMintNftInstruction<TProgram>)
  | ({
      instructionType: StatePassInstruction.UpdatePassLevel;
    } & ParsedUpdatePassLevelInstruction<TProgram>);
