/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from "@solana/kit";
import { STATE_PASS_PROGRAM_ADDRESS } from "../programs";

/** InvalidLevel: The provided level is invalid or the maximum level has been reached. */
export const STATE_PASS_ERROR__INVALID_LEVEL = 0x1770; // 6000

export type StatePassError = typeof STATE_PASS_ERROR__INVALID_LEVEL;

let statePassErrorMessages: Record<StatePassError, string> | undefined;
if (process.env.NODE_ENV !== "production") {
  statePassErrorMessages = {
    [STATE_PASS_ERROR__INVALID_LEVEL]: `The provided level is invalid or the maximum level has been reached.`,
  };
}

export function getStatePassErrorMessage(code: StatePassError): string {
  if (process.env.NODE_ENV !== "production") {
    return (statePassErrorMessages as Record<StatePassError, string>)[code];
  }

  return "Error message not available in production bundles.";
}

export function isStatePassError<TProgramErrorCode extends StatePassError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode,
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    STATE_PASS_PROGRAM_ADDRESS,
    code,
  );
}
